### ISSUE TITLE
ALWAYS BETTER TO FOLLOW OOPS CONCEPTS IN CODING 

### ISSUE THREAD

**Issue by yasirysr47** [sky0walker99/WeCode-Ai-Learning#5]
https://github.com/sky0walker99/WeCode-Ai-Learning/blob/a2ab0cfde26cb3bbe07d31a6d00f973e881974d4/backend/src/main.py#L13

**Comment by sky0walker99** [comment]
I have fixed this in ccca91b9d65d15f4e44c107f39420300d38aa0c9
