### ISSUE TITLE
This will always choose only one model

### ISSUE THREAD

**Issue by yasirysr47** [sky0walker99/WeCode-Ai-Learning#6]
https://github.com/sky0walker99/WeCode-Ai-Learning/blob/a2ab0cfde26cb3bbe07d31a6d00f973e881974d4/backend/src/main.py#L146

**Comment by Alen-121** [comment]
It will change accordingly through sentimental analysis

**Comment by Alen-121** [comment]
It will change accordingly through sentimental analysis
